ablog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('bloggers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloggers/urls.py
from django.urls import path
from .views import UserRegisterView, UserEditView, PasswordsChangeView, ShowProfilePageView, EditProfilePageView
from django.contrib.auth import views as auth_views

app_name = 'bloggers'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change_password.html'), name='change_pass'),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name='profile_page'),
    path('<int:pk>/edit_profile_page/', EditProfilePageView.as_view(), name='edit_profile_page'),
]

myblog/urls.py
from django.urls import path
from .views import HomeView, PostDetailView, PostCreateView, PostEditView, PostDeleteView, CategoryCreateView, CategoryView, CategoryListView, LikeView

app_name = 'myblog'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('article/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('add_post/', PostCreateView.as_view(), name='add_post'),
    path('add_category/', CategoryCreateView.as_view(), name='category'),
    path('article/edit/<int:pk>', PostEditView.as_view(), name='edit'),
    path('article/delete/<int:pk>', PostDeleteView.as_view(), name='delete'),
    path('category/<str:cats>/', CategoryView, name='categoryview'),
    path('category_list/', CategoryListView, name='categorylist'),
    path('like/<int:pk>', LikeView, name='like_post'),
]

myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

from datetime import datetime, date

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myblog:home')


class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to="media/")
    title_tag = models.CharField(max_length=255, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    post_date = models.DateField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    snippet = models.CharField(max_length=255)
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title + " by " + str(self.author)

    def get_absolute_url(self):
        return reverse('myblog:detail', args=(str(self.id)))


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    bio = models.TextField(blank=True)
    profile_pic = models.ImageField(blank=True, null=True, upload_to="profile/")
    website_url = models.CharField(max_length=255, null=True, blank=True)
    facebook_url = models.CharField(max_length=255, null=True, blank=True)
    twitter_url = models.CharField(max_length=255, null=True, blank=True)
    instagram_url = models.CharField(max_length=255, null=True, blank=True)


    def __str__(self):
        return str(self.user)

myblog/forms.py
from django import forms
from .models import Post, Category

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'header_image', 'title_tag', 'author', 'category', 'body', 'snippet')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'header_image': forms.FileInput(attrs={'type': 'file'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={
                'class': 'form-control',
                'value': '',
                'id': 'author',
                'type': 'hidden',
                }),
        #    'author': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'}),      
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'header_image', 'body', 'snippet')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'header_image': forms.FileInput(attrs={'type': 'file'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'}), 
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'categoryName',
                'type': 'text',
            })
        }

myblog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy

from .models import Post, Category
from .forms import PostForm, EditForm, CategoryForm

class HomeView(generic.ListView):
    model = Post
    template_name = 'myblog/home.html'
    queryset = Post.objects.order_by('-id').all()

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context['cat_menu'] = cat_menu
        return context


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'myblog/detail.html'

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)

        post = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = post.total_likes()

        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['cat_menu'] = cat_menu
        context['total_likes'] = total_likes
        context['liked'] = liked

        return context


class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'myblog/add_post.html'


class CategoryCreateView(generic.CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'myblog/add_category.html'


class PostEditView(generic.UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'myblog/update_post.html'


class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'myblog/delete_post.html'
    success_url = reverse_lazy('myblog:home')


def CategoryView(request, cats):
    cat_menu = Category.objects.all()
    category = Category.objects.filter(name=cats.replace('-', ' ')).first()
    post = Post.objects.filter(category=category).order_by('-id')
    return render(request, 'myblog/categories.html', {
        'post_categories': post, 
        'category': category,
        'cat_menu': cat_menu,
        })

def CategoryListView(request):
    cat_menu_list = Category.objects.all()
    return render(request, 'myblog/category_list.html', {
        'cat_menu_list': cat_menu_list,
    })

def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:      
        post.likes.add(request.user)
        liked = True

    return redirect('myblog:detail', pk=post.id)

myblog/templates/myblog/add_category.html
{% extends 'base.html' %}

{% block title %}Create Category{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    <section class="container my-4">
        <h1>Create A Category</h1>
        <div class="row">
            <div class="col-10">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="categoryName" class="col-sm-2 col-form-label">{{ form.name.label }}:</label>
                        <div class="col-sm-10">
                            {{ form.name }}
                        </div>
                    </div>
                    <button class="btn btn-primary mt-4" type="submit">Add</button>
                </form>
            </div>
        </div>
    </section>
{% else %}
    <div class="container mt-4">
        <div class="alert alert-warning text-center" role="alert">
            <h1>Login Required</h1>
            <a href={% url 'login' %} class="btn btn-primary">Login</a>
        </div>
    </div>
{% endif %}


{% endblock %}

myblog/templates/myblog/add_post.html
{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    <section class="container my-4">
        <h1>Create A Blog Post</h1>
        <div class="row">
            <div class="col-10">
                <form action="" method="post" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.media }}
                        {{ form.as_p }}
                    </div>
                    <button class="btn btn-primary" type="submit">Post</button>
                </form>
            </div>
        </div>
    </section>

    <script>
        var name = '{{ user.id }}';
        document.getElementById("author").value = name;

    </script>
{% else %}
    <div class="container mt-4">
        <div class="alert alert-warning text-center" role="alert">
            <h1>Login Required</h1>
            <a href={% url 'login' %} class="btn btn-primary">Login</a>
        </div>
    </div>
{% endif %}


{% endblock %}

myblog/templates/myblog/categories.html
{% extends 'base.html' %}

{% block title %}HomePage{% endblock %}

{% block content %}

<div class="container bg-light my-4">
    <h1>{{ category|capfirst }}</h1>
    <div class="row">
        {% if post_categories %}
            {% for post in post_categories %}
                <div class="col-8 offset-2 my-3 text-center">
                    <h2><a href="{% url 'myblog:detail' post.id %}">{{ post.title|capfirst }}</a></h2>
                    <p class="text-muted">posted by: {{ post.author }} on {{ post.post_date }}</p>
                    <p class='lead'>{{ post.body|slice:":200" }}</p>
                    {% if post.author == user %}
                        <p><a href="{% url 'myblog:edit' post.id %}" class="btn btn-outline-primary btn-block btn-sm">Edit</a></p>
                        <p><a href="{% url 'myblog:delete' post.id %}" class="btn btn-outline-primary btn-block btn-sm">Delete</a></p>
                    {% endif %}
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-8 offset-2 my-3 text-center">
                <h2>No posts in this category</h2>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

myblog/templates/myblog/category_list.html
{% extends 'base.html' %}

{% block title %}Blog Categories{% endblock %}

{% block content %}

<div class="container-fluid mt-4 p-4 text-center">
    <h1>Blog Categories</h1>
    {% for category in cat_menu_list %}
        <ul class='list-unstyled'>
            <a class="text-dark h4" href="{% url 'myblog:categoryview' category.name|slugify %}">{{ category.name|capfirst }}</a>
        </ul>
    {% endfor %}
</div>

{% endblock %}

myblog/templates/myblog/delete_post.html
{% extends 'base.html' %}

{% block title %}Delete - {{ post.title|capfirst }}{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    {% if post.author.id == user.id %}
        <section class="container my-4 text-center">
            <h1>Delete - {{ post.title|capfirst }}</h1>
            <div class="row">
                <div class="col-8 offset-2">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                        </div>
                        <div class="alert alert-warning text-center" role="alert">
                            Are You Sure?
                        </div>
                        <button class="btn btn-primary btn-block" type="submit">Delete</button>
                    </form>
                </div>
            </div>
        </section>
    {% else %}
        <div class='container mt-4'>
            <div class="alert alert-warning text-center" role="alert">
                <h1>Invalid User</h1>
            </div>
        </div>
    {% endif %}

{% else %}
    <div class="container mt-4">
        <div class="alert alert-warning text-center" role="alert">
            <h1>Login Required</h1>
            <a href={% url 'login' %} class="btn btn-primary">Login</a>
        </div>
    </div>
{% endif %}
{% endblock %}

myblog/templates/myblog/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<div class="container-fluid mt-4 p-4">
    <div class="row text-center">
        <div class="col">
            <h1>{{ post.title }}</h1>
            <p class="text-muted"><a href="{% url 'myblog:categoryview' post.category %}">{{ post.category|capfirst }}</a></p>
            <p class="text-muted">posted by: {{ post.author }} on {{ post.post_date }}</p>
            {% if post.header_image %}
                <img src="{{ post.header_image.url }}" alt="" class='img-fluid'>
            {% endif %}
            <p>{{ post.body|safe }}</p>
            <br />
            {% if user.is_authenticated %}
                <div class="row d-flex justify-content-center mb-4">
                    <form action={% url 'myblog:like_post' post.pk %} method="POST">
                        {% csrf_token %}
                        {% if liked %}
                            <button type="submit" name='post_id' value='{{ post.id }}' class="btn btn-primary btn-sm">{{ total_likes}} <i class="fas fa-thumbs-down"></i> Like</button>  
                        {% else %}
                            <button type="submit" name='post_id' value='{{ post.id }}' class="btn btn-outline-primary btn-sm">{{ total_likes}} <i class="fas fa-thumbs-up"></i> Like
                            </button>
                        {% endif %}
                </div>
            {% endif %}
            {% if post.author == user %}
                <p><a href={% url 'myblog:edit' post.id %} class="btn btn-primary" style="width: 10rem;">Edit</a>
                <a href={% url 'myblog:delete' post.id %} class="btn btn-primary" style="width: 10rem;">Delete</a></p>
            {% endif %}
        </div>
    </div>
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-2 fill">
                {% if post.author.profile.profile_pic %}
                    <a href="{% url 'bloggers:profile_page' post.author.profile.id %}"><img src="{{ post.author.profile.profile_pic.url }}" alt="" class='img-thumbnail ml-2'></a>
                {% else %}
                    <a href="{% url 'bloggers:profile_page' post.author.profile.id %}"><img src="{% static 'myblog/image/default.jpg' %}" alt="" class='img-thumbnail ml-2'></a>
                {% endif %}
            </div>
            <div class="col-md-10">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'bloggers:profile_page' post.author.profile.id %}">{{ post.author.first_name|capfirst }} {{ post.author.last_name|capfirst }}</a></h5>
                    <p>
                        {% if post.author.profile.website_url %}
                            <a href="{{ post.author.profile.website_url }}"><i class="fas fa-globe"></i></a>
                        {% endif %}
                        {% if post.author.profile.facebook_url %}
                            <a href="{{ post.author.profile.facebook_url }}"><i class="fab fa-facebook"></i></a>
                        {% endif %}
                        {% if post.author.profile.twitter_url %}
                            <a href="{{ post.author.profile.twitter_url }}"><i class="fab fa-twitter"></i></a>
                        {% endif %}
                        {% if post.author.profile.instagram_url %}
                            <a href="{{ post.author.profile.instagram_url }}"><i class="fab fa-instagram-square"></i></a>
                        {% endif %}
                    </p>
                    <p class="card-text">{{ post.author.profile.bio }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

myblog/templates/myblog/home.html
{% extends 'base.html' %}

{% block title %}HomePage{% endblock %}

{% block content %}

<div class="container bg-light my-4">
    <h1>Posts</h1>
    <div class="row">
        {% for post in object_list %}
            <div class="col-8 offset-2 my-3 text-center">
                <h2><a href="{% url 'myblog:detail' post.id %}">{{ post.title|capfirst }}</a></h2>
                <p class="text-muted"><a href="{% url 'myblog:categoryview' post.category|slugify %}">{{ post.category|capfirst }}</a>
                <p class="text-muted">posted by: {{ post.author }} on {{ post.post_date }}</p>
                <p>{{ post.snippet }}</p>
                {% if post.author == user %}
                    <p><a href={% url 'myblog:edit' post.id %} class="btn btn-outline-primary btn-block btn-sm">Edit</a></p>
                    <p><a href={% url 'myblog:delete' post.id %} class="btn btn-outline-primary btn-block btn-sm">Delete</a></p>
                {% endif %}
                <hr>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

myblog/templates/myblog/update_post.html
{% extends 'base.html' %}

{% block title %}Edit - {{ post.title|capfirst }}{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    {% if post.author.id == user.id %}
        <section class="container my-4">
            <h1>Edit - {{ post.title|capfirst }}</h1>
            <div class="row">
                <div class="col-10">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.media }}
                            {{ form.as_p }}
                        </div>
                        <button class="btn btn-primary" type="submit" style="width: 10rem;">Edit</button>
                    </form>
                </div>
            </div>
        </section>
    {% else %}
        <div class='container mt-4'>
            <div class="alert alert-warning text-center" role="alert">
                <h1>Invalid User</h1>
            </div>
        </div>
    {% endif %}

{% else %}
    <div class="container mt-4">
        <div class="alert alert-warning text-center" role="alert">
            <h1>Login Required</h1>
            <a href={% url 'login' %} class="btn btn-primary">Login</a>
        </div>
    </div>
{% endif %}

{% endblock %}