ablog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('bloggers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloggers/urls.py
from django.urls import path
from .views import UserRegisterView, UserEditView, PasswordsChangeView, ShowProfilePageView, EditProfilePageView
from django.contrib.auth import views as auth_views

app_name = 'bloggers'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change_password.html'), name='change_pass'),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name='profile_page'),
    path('<int:pk>/edit_profile_page/', EditProfilePageView.as_view(), name='edit_profile_page'),
]

myblog/urls.py
from django.urls import path
from .views import HomeView, PostDetailView, PostCreateView, PostEditView, PostDeleteView, CategoryCreateView, CategoryView, CategoryListView, LikeView

app_name = 'myblog'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('article/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('add_post/', PostCreateView.as_view(), name='add_post'),
    path('add_category/', CategoryCreateView.as_view(), name='category'),
    path('article/edit/<int:pk>', PostEditView.as_view(), name='edit'),
    path('article/delete/<int:pk>', PostDeleteView.as_view(), name='delete'),
    path('category/<str:cats>/', CategoryView, name='categoryview'),
    path('category_list/', CategoryListView, name='categorylist'),
    path('like/<int:pk>', LikeView, name='like_post'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://kit.fontawesome.com/6ad3ddd4bb.js" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'myblog/css/styles.css' %}">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'myblog:home' %}"><i class="far fa-comment-alt"></i> My Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myblog:home' %}">Home</a>
          </li>
          {% if cat_menu %}
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Categories
              </a>
              <div class="dropdown-menu">
                {% for category in cat_menu %}
                  <a class="dropdown-item" href="{% url 'myblog:categoryview' category.name|slugify %}">{{ category.name|capfirst }}</a>
                {% endfor %}
              </div>
            </li>
          {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myblog:categorylist' %}">Category List</a>
              </li>
          {% endif %}
          {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myblog:add_post' %}">Post</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myblog:category' %}">Categories</a>
            </li>
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Profile
              </a>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'bloggers:profile_page' user.id %}">Profile Page</a>
                  <a class="dropdown-item" href="{% url 'bloggers:edit_profile_page' user.id %}">Edit Profile Page</a>
              </div>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'bloggers:register' %}">Register</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    
    {% block content %}{% endblock %}

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>